### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ultraflame4** [UpGado/ascii_racer#3]
Where to get ncurses modules

**Comment by MikeBreytenbach** [comment]
pip install ncurses

On Windows, you're going to need [Cygwin](https://www.cygwin.com/) or run it through Windows 10's Linux subsystem.

**Comment by explosion33** [comment]
Have you tried running `pip install curses` In your console.

**Comment by sh1ftsh** [comment]
Hello, it seems that curses is in standard library, I don't know about window's one, but it work pretty fine on my linux computer

**Comment by UpGado** [comment]
As @MikeBreytenbach  suggested, Cygwin or a Linux subsystem will fix the issue. You can also try following what u/harryomharry suggested on [reddit](https://www.reddit.com/r/Python/comments/cpmll6/made_a_racing_game_that_runs_in_terminal_100/ewsi1n6/ ). If anyone has access to a Windows computer and can test it out, that would be very helpful, as I don't have immediate access to one.

**Comment by UpGado** [comment]
Just tested `windows-curses` for Windows and it seems to work. Try re-installing the latest version of `asciiracer` using pip. Closing this issue now, but feel free to reopen if the issue is not solved.

**Comment by ultraflame4** [comment]
> pip install ncurses
> 
> On Windows, you're going to need [Cygwin](https://www.cygwin.com/) or run it through Windows 10's Linux subsystem.

Thanks i try that rn
